import { EmbedBuilder, SlashCommandBuilder } from 'discord.js';
import { braveAnswerSummary } from '../helpers/braveSearch.js';

const MAX_DESCRIPTION_LENGTH = 4000;
// Summary text is LLM-generated from arbitrary web content, so strip Markdown
// control characters before dropping it into an embed to avoid broken formatting.
const MARKDOWN_CHARS_REGEX = /[*_~`|]/g;

function sanitize(text) {
  return text.replace(MARKDOWN_CHARS_REGEX, '');
}

function truncate(text, length) {
  return text.length > length ? `${text.slice(0, length - 1)}…` : text;
}

export default {
  data: new SlashCommandBuilder()
    .setName('search')
    .setDescription('Gets an AI-generated overview answer (via Brave Search) for a query.')
    .addStringOption((option) =>
      option.setName('query').setDescription('What to ask or search for.').setRequired(true)
    ),

  async execute(interaction) {
    await interaction.deferReply();

    const query = interaction.options.getString('query');

    let result;
    try {
      result = await braveAnswerSummary(query);
    } catch (error) {
      console.error('Brave Search error:', error);
      return interaction.editReply('Search failed — the search provider may be down or rate-limited.');
    }

    if (!result.available) {
      return interaction.editReply(
        `No AI overview available for **${sanitize(query)}**. Try rephrasing it as a question.`
      );
    }

    const embed = new EmbedBuilder()
      .setColor(0xfb542b)
      .setTitle(`AI overview: "${sanitize(query)}"`)
      .setDescription(truncate(sanitize(result.text), MAX_DESCRIPTION_LENGTH))
      .setFooter({ text: 'Generated by Brave Search Answers — may be inaccurate' });

    await interaction.editReply({ embeds: [embed] });
  },
};
